# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WiuvIIIKppKV8a2AdcrqxoBZ5CxzPu62r+9kJnEiMlNujQpDJ+tCARHCB2aIBGr/hGhM5XjCOosjvLuzd1IqKpcPBHhPamdj0YrpjA8vBLtDqlOsMRm1t4ySuXzY3EyQeqYMrC2FinCRL70TidjFZJPZ2mUxoSAK2hGZ3PcvGdt8yjm4bxBwXU0ArE4kFE6TD9UuvyolQ4q4y3zor1j12ypj3UBkpf5+n5dAcUGz01N7ia5svdsCTiCOKQA+NoB68hpXPPB0sQ5WDw/vsJzJMx/NEDGJbZUT48MRMRTV6wK4GhR9Pc9m9jFbiMg19bk8jvLiBacCrC6C1QCcDyQfsP5liMfuRbIlg1DyvpGx/FbZXPS5wMwM+J5xrv5KMcmPnfUf9HIax/O/DbJUTNqZV/UnPQHVKeoSiUpBOpucTWKPtab22JMXL+cuqnmxsIEdtOUsOz3+e2E9MBT8SVmxe2vI6QqEINdJEj6opNQyECkQjf/fprhyUt1nf2eckxTaDPpFd0/2wOwv/puQqODDgIDZH7rYX0IaTQ/licqYa5DPpGHQKdmwA6U6gcatkaJh9wy/P3NBe+Daf3LPP14wG0agD3Mz/NjkPnMMmJk52ORYkGBefpkBSniEre6GBMnm+limGrBkWp7Pj1f2oKQ54MtXZS/beLkfqMi/YqbM6OY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
