appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: WiuvIIIKppKV8a2AdcrqxoBZ5CxzPu62r+9kJnEiMlNujQpDJ+tCARHCB2aIBGr/hGhM5XjCOosjvLuzd1IqKpcPBHhPamdj0YrpjA8vBLtDqlOsMRm1t4ySuXzY3EyQeqYMrC2FinCRL70TidjFZJPZ2mUxoSAK2hGZ3PcvGdt8yjm4bxBwXU0ArE4kFE6TD9UuvyolQ4q4y3zor1j12ypj3UBkpf5+n5dAcUGz01N7ia5svdsCTiCOKQA+NoB68hpXPPB0sQ5WDw/vsJzJMx/NEDGJbZUT48MRMRTV6wK4GhR9Pc9m9jFbiMg19bk8jvLiBacCrC6C1QCcDyQfsP5liMfuRbIlg1DyvpGx/FbZXPS5wMwM+J5xrv5KMcmPnfUf9HIax/O/DbJUTNqZV/UnPQHVKeoSiUpBOpucTWKPtab22JMXL+cuqnmxsIEdtOUsOz3+e2E9MBT8SVmxe2vI6QqEINdJEj6opNQyECkQjf/fprhyUt1nf2eckxTaDPpFd0/2wOwv/puQqODDgIDZH7rYX0IaTQ/licqYa5DPpGHQKdmwA6U6gcatkaJh9wy/P3NBe+Daf3LPP14wG0agD3Mz/NjkPnMMmJk52ORYkGBefpkBSniEre6GBMnm+limGrBkWp7Pj1f2oKQ54MtXZS/beLkfqMi/YqbM6OY=}
